#!/bin/sh
NAME="CMD daemon"
DAEMON=/usr/sbin/cmd
PIDFILE=/var/run/`basename $DAEMON`.pid
CONF_NAME=cmd
PMOND_START="lipc-set-prop com.lab126.pmond start"
PMOND_STOP="lipc-set-prop com.lab126.pmond stop"
_FUNCTIONS=/etc/rc.d/functions

WIFION_FILE=/mnt/us/WIFION

[ -f ${_FUNCTIONS} ] && . ${_FUNCTIONS}

case "$1" in

   start)
		if [ -x "$DAEMON" ]; then
			msg "starting $NAME" I
			$PMOND_START $CONF_NAME
		fi
		;;

   stop)
		if [ -r "$PIDFILE" ]; then
			msg "stopping $NAME" I
			$PMOND_STOP $CONF_NAME
		fi
		;;
	*)
		msg "Usage: /etc/init.d/$NAME {start|stop}" W >&2
		exit 1
		;;
esac

exit 0

