#!/bin/sh

export PATH=/usr/sbin:${PATH}

_FUNCTIONS=/etc/rc.d/functions
[ -f ${_FUNCTIONS} ] && . ${_FUNCTIONS}

_EINK_BOOTSTRAP=/opt/eink/scripts/bootstrap-broadsheet

_EINK_WAVEFORM_VERSION=${EINK_PROC}/waveform_version

_EINK_WAVEFORM_UPDATE_FAILED_ERROR_CODE=0100
_EINK_WAVEFORM_UPDATE_ERROR_CODE_LEN=4

_REQ_FILE_SIZE=131072

_OUTFILE=/tmp/.ewu.out

_NO_LOGO=0
_REBOOT=1

_WAVEFORM_EINK_VERSION=
_WAVEFORM_FILE_VERSION=

_WAVEFORM_FILE_CKSUM_EMBEDDED=
_WAVEFORM_FILE_CKSUM_COMPUTED=

_WAVEFORM_FILE=
_WAVEFORM_FILE_BASENAME=

_COMMANDS_FILE=`ls /opt/eink/images/cmd0047_*.bin`

get_eink_waveform_version()
{
    _WAVEFORM_EINK_VERSION="`cat ${_EINK_WAVEFORM_VERSION}`"
}

get_file_waveform_version()
{
    _WAVEFORM_FILE_VERSION="`eu waveform ${_WAVEFORM_FILE}`"
}

get_file_waveform_cksum()
{
    _WAVEFORM_FILE_CKSUM_EMBEDDED="`eu waveform -e ${_WAVEFORM_FILE}`"
    _WAVEFORM_FILE_CKSUM_COMPUTED="`eu waveform -c ${_WAVEFORM_FILE}`"
}

eips_update_msg()
{
    _EIPS_X_UPDATE_MSG=$(( (${SCREEN_X_RES}/${EIPS_X_RES} - ${#_WAVEFORM_FILE_VERSION}) ))
    _EIPS_Y_UPDATE_MSG=$(( (${SCREEN_Y_RES}/${EIPS_Y_RES} - 1) ))
    ${EIPS} ${_EIPS_X_UPDATE_MSG} ${_EIPS_Y_UPDATE_MSG} "${_WAVEFORM_FILE_VERSION}"
}

# Preflight the input parameters.
#
if ! ( eink_rom_is_flash ); then
    msg "device does not support waveform flashing" E
    exit ${EINK_ERR_RECOVERABLE}
fi

if [ $# -lt 1 ] || [ $# -gt 2 ]; then
    msg "usage: $0 [-no_reboot] waveform" E
    exit ${EINK_ERR_RECOVERABLE}
fi

if [ $# -eq 2 ]; then
    if [ "$1" = "-no_reboot" ]; then
        _WAVEFORM_FILE="$2"
        _REBOOT=0
    else
        msg "usage: $0 [-no_reboot] waveform" E
        exit ${EINK_ERR_RECOVERABLE}
    fi
else
    _WAVEFORM_FILE="$1"
fi

if [ ! -f "$_WAVEFORM_FILE" ]; then
    msg "cannot open waveform ${_WAVEFORM_FILE}" E
    exit ${EINK_ERR_RECOVERABLE}
fi

_WAVEFORM_FILE_BASENAME=`basename ${_WAVEFORM_FILE}`
_SIZE="`cat ${_WAVEFORM_FILE} | wc -c | sed 's/^  *//'`"

if [ ${_SIZE} -gt ${_REQ_FILE_SIZE} ]; then
    msg "waveform ${_WAVEFORM_FILE} is not the required size (needs to be ${_REQ_FILE_SIZE} bytes or less)" E
    exit ${EINK_ERR_RECOVERABLE}
fi

if [ ! -f "${_COMMANDS_FILE}" ]; then
    msg "error: commands file ${_COMMANDS_FILE} could not be found" E
    exit ${EINK_ERR_RECOVERABLE}
fi

msg "flashing waveform ${_WAVEFORM_FILE}" I

# Stop the framework, leaving the screen as is, and stop the power daemon.
#
shutdown_framework $SHUTDOWN_FRAMEWORK_SCREEN_ASIS
stop_powerd

# Put the initial software-update screen up.
#
display_update_screen_initial
update_progressbar 10

# Print out existing (controller's) waveform info.
#
get_eink_waveform_version
update_progressbar 20

msg "Existing waveform version:" I
msg "  ${_WAVEFORM_EINK_VERSION}" I

# Print out waveform file's info.
#
msg "Waveform name:" I
msg "  ${_WAVEFORM_FILE_BASENAME}" I

msg "Waveform size:" I
msg "  ${_SIZE} bytes" I

get_file_waveform_version
update_progressbar 30

msg "Waveform version:" I
msg "  ${_WAVEFORM_FILE_VERSION}" I

get_file_waveform_cksum
update_progressbar 40

msg "Waveform checksum:" I
msg "  embedded is ${_WAVEFORM_FILE_CKSUM_EMBEDDED}" I
msg "  computed is ${_WAVEFORM_FILE_CKSUM_COMPUTED}" I

# Create composite waveform file.
#
_MSG="Updating waveform..."
msg "${_MSG}creating" I

rm -f ${_OUTFILE} 2>/dev/null
touch ${_OUTFILE}
cat ${_COMMANDS_FILE} > ${_OUTFILE}
cat ${_WAVEFORM_FILE} >>${_OUTFILE}
update_progressbar 50
eips_update_msg

# Flash waveform via bootstrapper.
#
msg "${_MSG}flashing" I
${_EINK_BOOTSTRAP} ${_OUTFILE}
_RES=$?

# Verify flash.
#
if [ ${_RES} -eq 0 ]; then

    msg "${_MSG}verifying" I
    ${EINK_FLASH_RESTART} ${_NO_LOGO}
    
    display_update_screen_initial
    update_progressbar 60
    eips_update_msg
    
    get_eink_waveform_version
    update_progressbar 75

    if [ "${_WAVEFORM_FILE_VERSION}" != "${_WAVEFORM_EINK_VERSION}" ]; then

        msg "${_MSG}ERROR:" E
        msg "  ${_WAVEFORM_FILE_VERSION} does not equal ${_WAVEFORM_EINK_VERSION}" E
        
        _RES=${EINK_ERR_UNRECOVERABLE}

    else
        
        rm -f ${_OUTFILE} 2>/dev/null
        update_progressbar 90
        
        msg "${_MSG}OK:" I
        msg "  ${_WAVEFORM_EINK_VERSION}" I
        
        update_progressbar 100
        
    fi
    
else

    msg "${_MSG}ERROR" E
    msg "  bootstrapper returned ${_RES}" E

fi

if [ ${_REBOOT} -eq 1 ]; then

    if [ ${_RES} -eq 0 ]; then

        display_update_screen_success
        echo "Rebooting in 5 seconds..."

        sleep 5

    else

        if [ ${_RES} -eq ${EINK_ERR_RECOVERABLE} ]; then
            _KEY_WAIT=R
            _KEY_WAIT_CODE=19
        
            _EIPS_X_UPDATE_FAILURE=$(( ((${SCREEN_X_RES}/${EIPS_X_RES} - ${_EINK_WAVEFORM_UPDATE_ERROR_CODE_LEN})/2 - 1) ))
        
            echo "Please press the \"${_KEY_WAIT}\" key on the keyboard"
            echo "to restart the device."
            display_update_screen_failure
            ${EIPS} ${_EIPS_X_UPDATE_FAILURE} ${EIPS_Y_UPDATE_FAILURE} ${_EINK_WAVEFORM_UPDATE_FAILED_ERROR_CODE}
            eips_update_msg
        
            waitforkey ${_KEY_WAIT_CODE}
        fi

    fi

    reboot

fi
