#!/bin/sh
_FUNCTIONS=/etc/rc.d/functions
[ -f ${_FUNCTIONS} ] && . ${_FUNCTIONS}

_MNTLOG=/etc/sysconfig/mntlog
[ -f $_MNTLOG ] && . $_MNTLOG

UPTIME=`sed -e "s/ [0-9].*//;s/\([0-9]*\)\..*/\1/" < /proc/uptime`
DEADZONE=30

loginfo_memusedump()
{
	ps axo stat,pgrp,ppid,pid,rss,pcpu,comm hww | while read item; do
		stat=`echo $item | awk '/^/ { print $1 }'`;
		pgrp=`echo $item | awk '/^/ { print $2 }'`;
		ppid=`echo $item | awk '/^/ { print $3 }'`;
		pid=`echo $item | awk '/^/ { print $4 }'`;
		rss=`echo $item | awk '/^/ { print $5 }'`;
		pcpu=`echo $item | awk '/^/ { print $6 }'`;
		args=`echo $item | awk '/^/ { print $7 }'`;

		# special handling of ppd on Clif's request
		if [ "x${args}" == "xpppd" ]; then
			msg "stat=$stat,ppid=$ppid,pid=$pid,rss=$rss,pcpu=$pcpu,args=$args:" I "psinfo"
		fi

		# Removing init (pid=1)
		# Removing kthread (pid=2)
		# Removing kernel processes (ppid=2)
		if [ ${pid} != 1 ] && [ ${pid} != 2 ] && [ ${ppid} != 2 ] && [ ${rss} -gt 1024 ] ; then
			msg "stat=$stat,ppid=$ppid,pid=$pid,rss=$rss,pcpu=$pcpu,args=$args:" I "psinfo"
		fi
	done
}

is_powerd_uninterruptible()
{
	uninterruptible=0

	item=`ps axo stat,comm hww | grep powerd`
	stat=`echo $item | awk '/^/ { print $1 }'`;
	args=`echo $item | awk '/^/ { print $2 }'`;

	if [ "$args" == "powerd" ]; then
		echo "$stat" | grep D 2>&1 >/dev/null
		if [ "$?" == "0" ]; then
			uninterruptible=1
		fi
	fi
}

loginfo_checkpowerd()
{
	is_powerd_uninterruptible

	if [ "$uninterruptible" == "1" ] ; then
		sleep 5

		is_powerd_uninterruptible
		if [ "$uninterruptible" == "1" ] ; then
			msg "powerd is $stat, purposefully rebooting" C "DslReboot"
			reboot
			exit 0
		fi
	fi
}

loginfo_mounts()
{
	df | tail -n+2 | awk '{ print "I mntinfo:mounts:dev=" $1 ", total=" $2 ", used=" $3 ", mount=" $6 ":" }' | logger
}

loginfo_tmpfs()
{
	freekilo=`df /var/tmp | grep rwfs | awk '/^/ { print $4 }'`;
	msg "tmpfsFreeSpace=${freekilo}kB:" I
}

loginfo_localVars()
{
	freekilo=`df ${MNTLOG_MP} | grep ${MNTLOG_DEV} | awk '/^/ { print $4 }'`;
	msg "localVarsFreeSpace=${freekilo}kB:" I
}

loginfo_cvmtotmem()
{
	msg "memSize=$1:" W cvmtotmem
	loginfo_cvmreset
}

loginfo_cvmreset()
{
	msg "Purposefully restarting CVM" E killtoolargecvm
	killall -9 cvm
}

loginfo_processtoobig()
{
	msg "memSize=$2:" W $1toolarge
	lipc-send-event com.lab126.hal processTooLarge -s $1
}

loginfo_systotmem()
{
	msg "memSize=$1:" W systemtoolarge
	loginfo_cvmreset
}

loginfo_sysloadavg()
{
	msg "timeframe=$1,value=$2:" I loadAverage
}

loginfo_keycount()
{
	msg ":logging keys count" I logKeyCount; sleep 1
	echo "keycnt" > /proc/keypad
}

loginfo_essentials()
{
	_USB_PHY=/sys/devices/platform/arc_udc/manufacturer
	usb_phy="unknown"

	if [ -e ${_USB_PHY} ]; then
		usb_phy=`cat ${_USB_PHY}`
	fi

	# HW info
	msg "boardID=`cat /proc/board_id | sed 's/\(....\).*/\1/'`:`productid` `hwbuildid` device - rev `hwrevision`" I devhw
	msg ":USB PHY built by ${usb_phy}" I devhwphy

	# SW info
	msg ":Original `cat /etc/version.txt`" I devsworig
	msg ":OTA  `cat /etc/prettyversion.txt`" I devswota

	# time related stuff
	lto=`lipc-get-prop com.lab126.wan localTimeOffset`
	ret=$?
	if [ "x$ret" == "x0" ]; then
		if  [ "x$lto" == "x-1" ]; then
			msg "retrieved local time offset but wand is yet to yield a meaningful value running" W ltoisnotsetyet
		else
			msg "lto=$lto: local time offset has been read" I ltoget
		fi
	elif [ "x$ret" == "x3" ]; then
		msg "cannot retrieve local time offset - wand not running" W ltofailwandoff
	else
		msg "cannot retrieve local time offset - unknown error " E ltofailunknowerror
	fi
}

loginfo_kitchensink()
{
	loginfo_memusedump
	loginfo_tmpfs
	loginfo_localVars
	loginfo_essentials
	loginfo_mounts

	lipc-probe -av | logger -t "lipc-props: I lipc-props:prop:"
}

# Bailing out when kicked off to close to boot time
if [ $UPTIME -lt $DEADZONE ]; then
	if ! [ "x$2" = "x--force" ]; then
		exit 1;
	fi
fi

case "$1" in

	memusedump)
		loginfo_memusedump
		exit 0
		;;
	tmpfs)
		loginfo_tmpfs
		exit 0
		;;
	localVars)
		loginfo_localVars
		exit 0
		;;
	cvmtotmem)
		loginfo_cvmtotmem $2
		exit 0
		;;
	processtoobig)
		loginfo_processtoobig $2 $3
		exit 0
		;;
	systotmem)
		loginfo_systotmem $2
		exit 0
		;;
	sysloadavg)
		loginfo_sysloadavg $2 $3
		exit 0
		;;
	keycount)
		loginfo_keycount
		exit 0
		;;
	essentials)
		loginfo_essentials
		exit 0
		;;
	powerdcheck)
		loginfo_checkpowerd
		exit 0
		;;
	mounts)
		loginfo_mounts
		exit 0
		;;
	kitchensink)
		loginfo_kitchensink
		exit 0
		;;
	*)
		exit 1
		;;

esac
