#!/bin/sh

. /etc/rc.d/functions

FW_DIR="$1"
FW_CS=${FW_DIR}/firmware.md5 

local LC=`cat ${FW_CS} | wc -l`
local I=0

while [ ${I} -lt ${LC} ]; do

	read L
	if [ -n "${L}" ]; then
		local F=`echo ${L} | awk '{ print $2 }'`

		if [ -n "`echo ${F} | grep dtp600w`" ]; then

			local M=`echo ${L} | awk '{ print $1 }'`
			local FM=`md5sum "${FW_DIR}/${F}" | cut -d ' ' -f 1`

			if ! [ "${FM}" = "${M}" ]; then
				msg "checksum error for \"${F}\"" E "ceff"
				exit 1
			fi

		fi
	fi

	I=$((${I} + 1))

done <${FW_CS}

exit 0

