## This file defines what evetns are handled by lipc-daemon
## The format of the file is 
##<event name>   <event publisher>   <command to execute when event is received>
##
## NOTE: By default the event name and any parameters are passed to the script as arguments.  If you want to ignore the arguments,
## you must add a semi-colon (;) to the end of the script command.
##
usbConfigured     com.lab126.hal        echo "lock">/dev/null; echo "lock">/dev/null; echo "lock">/proc/accelerometer;
usbUnconfigured   com.lab126.hal        echo "unlock">/dev/null; echo "unlock">/dev/null; echo "unlock">/proc/accelerometer;
FrameworkStarted  com.lab126.framework  rm -f /var/local/system/.framework_retries /var/local/system/.framework_reboots
tzRequested       com.lab126.framework  settz
interfaceChange   com.lab126.cmd        /usr/sbin/updatetime & true
triggerTimeChange com.lab126.cmd        /usr/sbin/updatetime & true

## Uncomment the following line if you want to see when lipc-daemon received
## outOfScreenSaver event.  Useful for debugging out of suspend performance
#outOfScreenSaver    com.lab126.powerd  . /etc/rc.d/functions; msg "lipc-daemon got outOfScreenSaver at `date +%s`s" I; true;
