# This file defines what properties are exposed by lipc-daemon.
orientation r   cat /proc/accelerometer | xargs echo -n
usid r   cat /proc/usid | xargs echo -n
boardid r   cat /proc/boardid | xargs echo -n
version r   cat /etc/version.txt | xargs echo -n
waveformversion r cat /proc/eink_fb/waveform_version | xargs echo -n
date w   /usr/sbin/setdate
sendEvent w lipc-send-event com.lab126.system.event
