# tinyrot-files.conf
# This file contains the configuration for tinyrot script
# Each line has 
# 1) a filename that needs to be rotated
# 2) a maxminum allowed storage usage for the 
#    rotated backups of the file (compressed).
#    Maximum size is in kilobytes.
# 3) optional maximum size, in kb, of any rotated
#    backup file.  If specified, rotations are done
#    based on this size and not AGGR_COUNT.  The '-' 
#    character indicates this is optional.
#
# NOTE: Separate the filename and maxsize by ONE (1, one, unos)
# tab.  No fancy formatting please
/var/log/messages	256	-
/var/log/odotlite	2048	25
