#!/bin/sh

_FUNCTIONS=/etc/rc.d/functions

NAME="wifid"
DAEMON=/usr/sbin/wifid
PIDFILE=/var/run/`basename $DAEMON`.pid
CONF_NAME=wifid
PMOND_START="lipc-set-prop com.lab126.pmond start "
PMOND_STOP="lipc-set-prop com.lab126.pmond stop"
WIFIOFF_FILE=/mnt/us/WIFIOFF

[ -f ${_FUNCTIONS} ] && . ${_FUNCTIONS}

case "$1" in

   start)
        if ! internal_features_enabled || [ ! -f $WIFIOFF_FILE ]; then
            F=var/local/system/hid.csv ; [ -e /opt/$F -a ! -e /$F ] && cp /opt/$F /$F
            F=var/local/system/wifid.conf ; [ -e /opt/$F -a ! -s /$F ] && cp /opt/$F /$F
            if [ -x "$DAEMON" ]; then
                msg "starting $NAME" I
                $PMOND_START $CONF_NAME
            fi
        else
            msg "Not starting wifid - found WIFIOFF" I
        fi
        ;;

   stop)
        if [ -r "$PIDFILE" ]; then
            msg "stopping $NAME" I
            $PMOND_STOP $CONF_NAME
        fi
        ;;
    *)
        msg "Usage: /etc/init.d/$NAME {start|stop}" W >&2
        exit 1
        ;;
esac

exit 0

