#!/bin/sh

_FUNCTIONS=/etc/rc.d/functions
[ -f ${_FUNCTIONS} ] && . ${_FUNCTIONS}

DAEMON=/usr/bin/pmond
NAME=pmond
DAEMONUSER=root
DESC="Process Monitoring Daemon"

start_it_up()
{

  echo -n "Starting $DESC: "
  $STARTSTOPD -q -x $DAEMON -S 
}

shut_it_down()
{
  echo -n "Stopping $DESC: "
  $STARTSTOPD -q -K -x $DAEMON
}

case "$1" in
  start)
    start_it_up
  ;;
  stop)
    shut_it_down
  ;;
  restart|force-reload)
    shut_it_down
    sleep 1
    start_it_up
  ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
    exit 1
  ;;
esac

exit 0
