#!/bin/sh

_FUNCTIONS=/etc/rc.d/functions
[ -f ${_FUNCTIONS} ] && . ${_FUNCTIONS}

DAEMON=/usr/bin/lipc-daemon
NAME=lipc-daemon
DAEMONUSER=root
DAEMONARGS="-p /etc/lipc-daemon-props.conf -e /etc/lipc-daemon-events.conf"
DESC="lipc-daemon"

start_it_up()
{

  echo -n "Starting $DESC: "
  $STARTSTOPD -q -x $DAEMON -S -- $DAEMONARGS
}

shut_it_down()
{
  echo -n "Stopping $DESC: "
  $STARTSTOPD -q -K -x $DAEMON
  rm -f $PIDFILE
}

case "$1" in
  start)
    start_it_up
  ;;
  stop)
    shut_it_down
  ;;
  restart|force-reload)
    shut_it_down
    sleep 1
    start_it_up
  ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
    exit 1
  ;;
esac

exit 0
