#!/bin/sh

_FUNCTIONS=/etc/rc.d/functions
[ -f ${_FUNCTIONS} ] && . ${_FUNCTIONS}

DAEMON=/usr/sbin/crond
NAME=crond
DAEMONUSER=root
DESC="crond"

start_it_up()
{

  msg "starting $DESC" I
  $STARTSTOPD -q -x $DAEMON -S -- -c /etc/crontab/
}

shut_it_down()
{
  msg "stopping $DESC" I
  # Crond does not generate pidfile. Use name to kill it
  $STARTSTOPD -q -K -n $NAME
  rm -f $PIDFILE
}

case "$1" in
  start)
    start_it_up
  ;;
  stop)
    shut_it_down
  ;;
  restart|force-reload)
    shut_it_down
    sleep 1
    start_it_up
  ;;
  *)
    msg "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" W >&2
    exit 1
  ;;
esac

exit 0
