#! /bin/sh
PATH=/usr/sbin:/usr/bin:/sbin:/bin
_FUNCTIONS=/etc/rc.d/functions

[ -f ${_FUNCTIONS} ] && . ${_FUNCTIONS}

do_stop () {
	# kill the framework and clear the screen
	shutdown_framework $SHUTDOWN_FRAMEWORK_CLROFF_SCREEN

	${TINYROT} --force
	hwclock -u -w
	sync

	echo
	echo "Halting in 1 second..."
	echo
	sleep 1
	halt -d -f -p
}

case "$1" in
  start|restart|reload|force-reload)
	msg "argument '$1' not supported" W
	exit 3
	;;
  stop)
	do_stop
	;;
  *)
	msg "Usage: $0 stop" W
	exit 1
	;;
esac
