#!/bin/sh
_FUNCTIONS=/etc/rc.d/functions
[ -f ${_FUNCTIONS} ] && . ${_FUNCTIONS}

case "$1" in
	start|stop)
	    _t_init=$(sed -e 's/ .*/000/ ; s/\.\(...\).*/\1/' < /proc/uptime ) 
	    msg "time=$_t_init:boot time after init in milliseconds" I "initboot"
		;;
	restart|reload|force-reload)
		msg "argument '$1' not supported" W
		exit 3
		;;
	*)
		msg "Usage: $0 {start|stop}" W
		exit 1
		;;
esac
