#!/bin/sh

_FUNCTIONS=/etc/rc.d/functions
[ -f ${_FUNCTIONS} ] && . ${_FUNCTIONS}

NAME=webreader
DAEMON=/usr/bin/$NAME
DAEMONUSER=root
DESC="WebReader Daemon"
CONF_NAME=$NAME
PMOND_START="lipc-set-prop com.lab126.pmond start "
PMOND_STOP="lipc-set-prop com.lab126.pmond stop"
# Try normal kill first. Then if didn't work. An -9 kill will follow
KILL_WEBREADER="killall -q webreader"
KILL_WEBREADER_9="killall -q -9 webreader"

start_it_up()
{
  msg "Starting $DESC" I
  $PMOND_START $CONF_NAME
}

shut_it_down()
{
  msg "Stopping $DESC" I
  $PMOND_STOP $CONF_NAME
  $KILL_WEBREADER
  $KILL_WEBREADER_9
}

case "$1" in
  start)
    start_it_up
  ;;
  stop)
    shut_it_down
  ;;
  restart|force-reload)
    shut_it_down
    sleep 1
    start_it_up
  ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
    exit 1
  ;;
esac

exit 0
