#!/bin/sh
#####################################################################
## Purpose:
##   launcher script for wpa_supplicant
##

_FUNCTIONS=/etc/rc.d/functions
[ -f ${_FUNCTIONS} ] && . ${_FUNCTIONS}


WPA_IFACE=${IFACE:-"wlan0"}
WPA_SUP_BIN="/usr/bin/wpa_supplicant"
WPA_CLI_BIN="/usr/bin/wpa_cli"
WPA_PIDFILE="/var/run/wpa_supplicant.${WPA_IFACE}.pid"
WPA_LOGFILE="/var/log/wpa_supplicant.${WPA_IFACE}.log"
WPA_SUP_CONF="-t -c /var/local/system/wpa_supplicant.conf -i $WPA_IFACE -f $WPA_LOGFILE"


# quit if executables are not installed
if [ ! -x "$WPA_SUP_BIN" ] || [ ! -x "$WPA_CLI_BIN" ]; then
	msg "Error: Executable(s) missing" E >&2
	exit 2
fi

do_start () {
        # Wait for the driver to be loaded
        i=0
        while [ $i -lt 10 ]; do
            # Check to see if the driver is ready
             if is_wlan0_ready; then
                 wmiconfig -i wlan0 --setdbglogconfig --mmask=0xffff
                 break
             else 
                 sleep 2
             fi
             i=$(($i + 1))
        done
	start-stop-daemon -o -S -b -m -p $WPA_PIDFILE -x $WPA_SUP_BIN -- $WPA_SUP_CONF
	msg "wpa supplicant started" I
}

do_stop () {
	start-stop-daemon -o -K -p $WPA_PIDFILE -x $WPA_SUP_BIN
	msg "wpa supplicant stopped" W
}

do_forcestop () {
	start-stop-daemon -o -K -s KILL -p $WPA_PIDFILE -x $WPA_SUP_BIN
	msg "wpa supplicant force stopped" W
}

let MAX_LOG_SZ=1000000
let LOG_TAIL_SZ=256000
#
# trunc() function saves last $LOG_TAIL_SZ bytes
#

do_trunc () {
if [ ! -e "$1" ]; then return; fi

local siz=$(stat -c%s "$1")
local TEMP="/tmp/1"
    
if [ $siz -gt $MAX_LOG_SZ ];
then
     msg "Truncating file $1 from $siz bytes" W
     sk=`expr $siz - $LOG_TAIL_SZ`
     skb=`expr $sk / 1024`
#     echo $sk  $skb
     dd if="$1" of=$TEMP bs=1024 skip=$skb
     
     rm "$1"
     mv  $TEMP $1
fi
}



case $1 in 
	start)
	    do_trunc $WPA_LOGFILE
		do_start
		;;

	stop)
		do_stop
		;;
	
	forcestop)
		do_forcestop
		;;
	
	restart)
		do_stop
		sleep 2
        do_trunc $WPA_LOGFILE
		do_start
		;;
	*)
		msg "Usage: $0 {start|stop|restart}" W >&2
		exit 1
		;;
esac

exit 0
